import {execFileSync} from 'node:child_process';
import {mkdir,mkdtemp,writeFile,cp,readFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const args=process.argv.slice(2);
if(args.length && (args.length!==2 || args[0]!=='--output-root' || !args[1])) throw new Error('Usage: node scripts/check-package.mjs [--output-root directory]');
const outputRoot=args.length ? resolve(args[1]) : join(root,'artifacts');
await mkdir(outputRoot,{recursive:true});
const run=await mkdtemp(join(outputRoot,'package-check-'));
console.log(`Package verification directory: ${run}`);
const stage=join(run,'package'),consumer=join(run,'consumer');
await mkdir(stage);
await mkdir(consumer);
const tsc=join(root,'node_modules/typescript/bin/tsc');
execFileSync(process.execPath,[tsc,'-p',join(root,'tsconfig.json'),'--outDir',join(stage,'dist')],{cwd:root,stdio:'inherit'});
await cp(join(root,'package.json'),join(stage,'package.json'));
await cp(join(root,'README.md'),join(stage,'README.md'));
const npm=process.platform==='win32' ? 'npm.cmd' : 'npm';
const pack=JSON.parse(execFileSync(npm,['pack','--json','--ignore-scripts','--pack-destination',run],{cwd:stage,encoding:'utf8'}))[0];
await writeFile(join(consumer,'package.json'),JSON.stringify({private:true,type:'module',dependencies:{tunejs:`file:../${pack.filename}`}}));
execFileSync(npm,['install','--ignore-scripts','--no-audit','--no-fund'],{cwd:consumer,stdio:'inherit'});
await cp(join(root,'examples/shared/first-sound.js'),join(consumer,'first-sound.js'));
await writeFile(join(consumer,'check.mjs'),`import assert from 'node:assert/strict';
import {Engine} from 'tunejs';
import {browserAdapter} from 'tunejs/browser';
import {nativeAdapter} from 'tunejs/native';
import {softKeys,softDrums} from 'tunejs/presets';
import {firstSound} from './first-sound.js';
const sound=firstSound(browserAdapter());
assert.equal(sound.engine.state,'idle');
await sound.dispose();
const presetEngine=new Engine({adapter:browserAdapter()});
assert.equal(presetEngine.instrument(softKeys).maxVoices,16);
assert.equal(presetEngine.kit(softDrums).hits.length,3);
await presetEngine.dispose();
let creates=0;
const native=new Engine({adapter:nativeAdapter(()=>{creates++;throw new Error('Unexpected native activation');})});
assert.equal(native.state,'idle');
await native.dispose();
assert.equal(creates,0);
console.log('Packed ESM consumers passed');
`);
execFileSync(process.execPath,['check.mjs'],{cwd:consumer,stdio:'inherit'});
await writeFile(join(consumer,'check.ts'),`import {Engine,type Adapter} from 'tunejs';
import {browserAdapter} from 'tunejs/browser';
import {nativeAdapter} from 'tunejs/native';
import {softKeys,softDrums} from 'tunejs/presets';
const native: Adapter=nativeAdapter(()=>{throw new Error('Typecheck only');});
const idle=new Engine({adapter:native});
async function example() {
  const e=new Engine({adapter:browserAdapter()});
  const s=e.oscillator();
  s.connect(e.filter()).connect(e.gain()).connect(e.output);
  await e.start();
  s.play().stop();
  e.instrument(softKeys).play(['C4','E4'],{duration:{seconds:1}}).stop();
  const clip = await e.sample({ id: 'clip', url: '/clip.wav' });
  clip.play({ loop: true }).stop();
  e.instrument(softKeys).connect(e.delay({ time: { seconds: 0.3 } })).connect(e.reverb()).connect(e.pan({ pan: -0.3 })).connect(e.bus({ gainDb: -6 })).connect(e.output);
  e.kit(softDrums).play('kick');
  await e.dispose();
}
void idle;
void example;
`);
execFileSync(process.execPath,[tsc,'--ignoreConfig','--strict','--noEmit','--module','nodenext','--target','es2022','check.ts'],{cwd:consumer,stdio:'inherit'});
await writeFile(join(run,'consumer.html'),(await readFile(join(root,'examples/browser/index.html'),'utf8')).replaceAll('/dist/','./consumer/node_modules/tunejs/dist/').replace('/examples/shared/first-sound.js','./consumer/first-sound.js'));
const report={filename:pack.filename,size:pack.size,unpackedSize:pack.unpackedSize,entryCount:pack.entryCount,integrity:pack.integrity,cleanConsumer:'pass',directory:run,tarball:join(run,pack.filename),scope:'Fresh staged build; packed JS/TS imports and lazy activation only; no audio or native-device verification'};
await writeFile(join(run,'package-results.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
console.log(`Packed browser example: ${join(run,'consumer.html')}`);
